backend:
  name: git-gateway
  branch: master

collections:
  - label: "Team Members"
    label_singular: "Team Member"
    name: "members"
    folder: "data/members"
    create: true
    identifier_field: name
    extension: yml
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "LinkedIn", name: "linkedin", widget: "string"}
      - {label: "Sort Order", name: "sortOrder", widget: "number", valueType: "int"}

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
